prefit: ""
prefixNpc: "&f[&bNPC&f]"

messages:
  no-permission: "&c관리자 권한이 필요합니다."
  no-player: "&c플레이어만 사용 가능합니다."
  npc:
    save: "모든 npc를 저장했습니다."
    skin: "npc &b%arg1%&f의 스킨을 %arg2%의 스킨으로 변경했습니다."
    tp-player: "npc &b%arg1%&f을(를) 플레이어에게 이동시켰습니다."
    tp-location: "npc &b%arg1%&f을(를) X:%arg2% Y:%arg3% Z:%arg4%로 이동시켰습니다."
    add-default: "새로운 npc &b%arg1%&f을 생성했습니다."
    remove: "npc &b%arg1%&f을(를) 제거했습니다."
    list: "[%arg0%]"
    npc-save: "npc &b%arg0%&f을(를) 저장했습니다. (UUID : %arg1%)"
    npc-load: "npc &b%arg0%&f을(를) 불러왔습니다. (UUID : %arg1%)"
    overlapping-name: "중복되는 이름은 불가능합니다."